name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  
  pre-test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [2.7, 3.6, 3.8]
    runs-on:  ${{ matrix.os }}   
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

  builds:
    needs: pre-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [2.7, 3.6, 3.8]
    steps:
    - name: tests
      run: |
        python3 manage.py test
        
    